apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  type: LoadBalancer
  selector:
    app: explorer
  ports:
    - name: http
      port: 80
      targetPort: 8080
